import type { IsoDate, IsoDateTime } from './common';
import type { GradeId } from './grades';

/**
 * Application lifecycle. Enforced as a state machine by the API layer
 * (illegal transitions are rejected — see docs/ARCHITECTURE.md §6).
 *
 *   draft → submitted → payment_pending → under_review ─┬→ approved
 *                                    ↑                   └→ rejected
 *                            needs_correction ────┘
 */
export type ApplicationStatus =
  | 'draft'
  | 'submitted'
  | 'payment_pending'
  | 'under_review'
  | 'needs_correction'
  | 'approved'
  | 'rejected';

/**
 * The legal status transitions, enforced server-side by the API layer
 * (docs/ARCHITECTURE.md §6). Terminal states have no outgoing edges.
 * `rejected` is reachable from `needs_correction` so an admin reviewing a
 * correction can still reject the application outright.
 */
export const APPLICATION_TRANSITIONS: Record<ApplicationStatus, readonly ApplicationStatus[]> = {
  draft: ['submitted'],
  submitted: ['payment_pending'],
  payment_pending: ['under_review', 'rejected'],
  under_review: ['needs_correction', 'approved', 'rejected'],
  needs_correction: ['under_review', 'rejected'],
  approved: [],
  rejected: [],
};

/** Whether `from → to` is a legal application-status transition. */
export function canTransition(from: ApplicationStatus, to: ApplicationStatus): boolean {
  return APPLICATION_TRANSITIONS[from].includes(to);
}

export type PaymentStatus = 'pending' | 'verified' | 'needs_review' | 'rejected';

export type Gender = 'male' | 'female' | 'other' | 'prefer_not_to_say';

export type GuardianRelation = 'father' | 'mother' | 'legal_guardian' | 'other';

export interface ApplicationStudent {
  fullName: string;
  dateOfBirth: IsoDate;
  gender: Gender;
  email: string;
  phone: string;
}

export interface ApplicationGuardian {
  fullName: string;
  relation: GuardianRelation;
  phone: string;
  email?: string;
  occupation?: string;
}

export interface ApplicationAcademic {
  gradeId: GradeId;
  schoolName: string;
  schoolAddress?: string;
}

/** Demo payment reference — transaction ID is user-provided, verification simulated. */
export interface PaymentReference {
  method: 'mfs_demo';
  transactionId: string;
  amount: number;
  status: PaymentStatus;
  submittedAt: IsoDateTime;
  verifiedAt?: IsoDateTime | null;
}

export interface StatusHistoryEntry {
  status: ApplicationStatus;
  at: IsoDateTime;
  actor: string;
  note?: string;
}

/** A scholarship application record. Personal data stays behind the API layer. */
export interface Application {
  /** Generated by the API layer, e.g. "SS26-847291". */
  id: string;
  student: ApplicationStudent;
  guardian: ApplicationGuardian;
  academic: ApplicationAcademic;
  payment: PaymentReference;
  status: ApplicationStatus;
  statusHistory: StatusHistoryEntry[];
  correctionNote?: string | null;
  /** Owning demo-account user, when submitted while signed in. */
  ownerUserId?: string | null;
  createdAt: IsoDateTime;
  updatedAt: IsoDateTime;
}

/**
 * Public-safe projection for anonymous tracking by application ID.
 * Deliberately contains NO personal information (anti-enumeration).
 */
export interface ApplicationStatusView {
  id: string;
  status: ApplicationStatus;
  paymentStatus: PaymentStatus;
  submittedAt: IsoDateTime | null;
  updatedAt: IsoDateTime;
  correctionNote?: string | null;
}
